import { useMemo, useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { Check, ChevronRight, CircleHelp, Cloud, Fingerprint, KeyRound, LockKeyhole, ShieldCheck, Wallet, X } from 'lucide-react'
import { loadLocalWitness, replaceLocalWitness } from './lib/vault'
import { connectWallet, discoverWallets, submitProof, type MidnightProvider, type Network } from './lib/wallet'

const steps = ['Understand the ballot', 'Prepare local eligibility', 'Keep data private', 'Review disclosure', 'Connect 1AM', 'Generate proof', 'View receipt']
const ballotId = 'northward-housing-2026'

export default function App() {
  const reduceMotion = useReducedMotion()
  const [step, setStep] = useState(3)
  const [network, setNetwork] = useState<Network>('preview')
  const [witness, setWitness] = useState(() => loadLocalWitness())
  const [wallet, setWallet] = useState<{ provider: MidnightProvider; name: string; address?: string } | null>(null)
  const [state, setState] = useState<'ready' | 'connecting' | 'proving' | 'submitted' | 'error'>('ready')
  const [message, setMessage] = useState('Review the two public outputs before you continue.')
  const wallets = useMemo(() => discoverWallets(), [])

  const prepare = () => { setWitness(replaceLocalWitness('Local eligibility record')); setStep(2); setMessage('A private eligibility record is now held only on this device.') }
  const selectNetwork = (next: Network) => { setNetwork(next); setWallet(null); setState('ready'); setMessage(`Network changed to ${next}. Your wallet session was reset.`) }
  const connect = async () => { try { setState('connecting'); const result = await connectWallet(network); setWallet({ provider: result.provider, name: result.provider.name ?? 'Midnight wallet', address: result.address }); setStep(4); setState('ready'); setMessage('Wallet connected for this browser session only.') } catch (error) { setState('error'); setMessage(error instanceof Error ? error.message : 'Wallet connection failed.') } }
  const prove = async () => { if (!wallet) return connect(); try { setState('proving'); setStep(5); setMessage('Your wallet is generating a zero-knowledge proof locally. No vote or eligibility value is sent to this page.'); const result = await submitProof(wallet.provider, ballotId, network); setState('submitted'); setStep(6); setMessage(`Proof submitted as ${result.txId}. Waiting for finalization before showing a receipt.`) } catch (error) { setState('error'); setMessage(error instanceof Error ? error.message : 'Proof submission failed.') } }
  const transition = reduceMotion ? { duration: 0 } : { duration: .22, ease: 'easeOut' as const }
  return <div className="app-shell">
    <a className="skip-link" href="#workspace">Skip to voter workspace</a>
    <header className="topbar"><a className="brand" href="#top"><span aria-hidden="true">◒</span> Ballot Boreal</a><nav aria-label="Primary"><a href="#privacy">Privacy model</a><a href="#results">Public results</a><a href="#help">Help</a></nav><div className="network-status"><span className="status-dot" /> {network} <span className="divider" /> {wallet ? 'Wallet connected' : 'Wallet not connected'}</div></header>
    <main id="workspace" className="workspace">
      <aside className="step-rail" aria-label="Voting steps"><p className="eyebrow">Your voting journey</p>{steps.map((label, index) => <button key={label} className={index === step ? 'step current' : index < step ? 'step done' : 'step'} onClick={() => setStep(index)}><span>{index < step ? <Check size={14} /> : String(index + 1).padStart(2, '0')}</span>{label}</button>)}</aside>
      <section className="content"><div className="mobile-step">Step {step + 1} of {steps.length}</div><motion.div initial={{ opacity: 0, y: reduceMotion ? 0 : 8 }} animate={{ opacity: 1, y: 0 }} transition={transition}><p className="eyebrow">Step 4 — public disclosure</p><h1>See exactly what leaves your device.</h1><p className="lede">The ballot checks that you are eligible and have not voted before. It does not receive your identity, eligibility record, or vote selection.</p></motion.div>
        <section className="requirement card"><div><p className="eyebrow">Public requirement</p><h2>Northward Housing Cooperative · Annual board ballot</h2><p>Prove you hold an active membership credential issued before 1 September 2026. One valid proof is allowed per member.</p></div><span className="deadline">Closes 30 Sep · 18:00 UTC</span></section>
        <section id="privacy" className="boundary" aria-label="Privacy boundary"><div className="private-side"><div className="boundary-title"><LockKeyhole size={20} /><div><p className="eyebrow">Stays on your device</p><h2>Private witness</h2></div></div><ul><li>Your membership credential</li><li>Your vote selection</li><li>Credential expiration and issuer signature</li><li>Wallet-held proving material</li></ul><button className="text-button" onClick={prepare}>{witness ? `Replace local record · v${witness.version}` : 'Prepare local record'} <ChevronRight size={16} /></button></div><div className="public-side"><div className="boundary-title"><Cloud size={20} /><div><p className="eyebrow">Published to Midnight</p><h2>Minimal public receipt</h2></div></div><ul><li><strong>Eligibility: valid</strong> — no underlying attribute</li><li><strong>One-time nullifier</strong> — prevents a second vote</li><li>Ballot ID and finalized transaction ID</li><li>Public aggregate count</li></ul><p className="small">The nullifier is an unlinkable one-time value. It proves uniqueness without naming a voter.</p></div></section>
        <section className="review card"><div className="review-head"><div><p className="eyebrow">Disclosure review</p><h2>Two deliberate disclosures</h2></div><ShieldCheck size={28} /></div><div className="disclosure"><span>01</span><div><strong>Eligibility is valid</strong><p>The contract learns the requirement was met, not why.</p></div><Check size={18} /></div><div className="disclosure"><span>02</span><div><strong>One-time nullifier</strong><p>The contract rejects duplicates without knowing who voted.</p></div><Check size={18} /></div><div className="notice"><CircleHelp size={18} /><p>Your selection remains private. Final public results are aggregate-only until the election administrator opens them.</p></div></section>
        <section className="proof card"><div><p className="eyebrow">Proof status</p><h2>{state === 'submitted' ? 'Submission received — awaiting finalization' : state === 'proving' ? 'Generating your proof locally' : 'Ready when you are'}</h2></div><div className="proof-track"><span className={state === 'proving' || state === 'submitted' ? 'active' : ''}>Local check</span><span className={state === 'submitted' ? 'active' : ''}>Wallet submission</span><span>Network finalization</span></div><button className="primary" disabled={state === 'connecting' || state === 'proving'} onClick={prove}>{state === 'proving' ? 'Generating proof…' : wallet ? 'Generate and submit proof' : 'Connect 1AM to continue'} <ChevronRight size={17} /></button></section>
        <div role="status" className={`message ${state}`}>{state === 'error' ? <X size={18} /> : <Fingerprint size={18} />}{message}</div>
      </section>
      <aside className="utility-rail"><section className="wallet-card"><div className="utility-heading"><Wallet size={19} /><h2>Wallet session</h2></div><div className="network-tabs" role="tablist"><button aria-selected={network === 'preview'} onClick={() => selectNetwork('preview')}>Preview</button><button aria-selected={network === 'preprod'} onClick={() => selectNetwork('preprod')}>Preprod</button></div><p className="small">{wallet ? `${wallet.name}${wallet.address ? ` · ${wallet.address.slice(0, 8)}…` : ''}` : wallets.length ? `${wallets.length} provider found · 1AM preferred` : 'Looking for a UUID-keyed Midnight provider'}</p>{wallet ? <button className="secondary" onClick={() => { wallet.provider.disconnect?.(); setWallet(null); setMessage('Wallet disconnected from this session.'); }}>Disconnect session</button> : <button className="secondary" onClick={connect} disabled={state === 'connecting'}>{state === 'connecting' ? 'Connecting…' : 'Connect 1AM'}</button>}</section>
        <section className="gemini-card"><div className="utility-heading"><KeyRound size={19} /><h2>Policy guide</h2></div><p>Gemini can explain this public ballot rule in plain language.</p><div className="ai-boundary"><span>Gemini sees</span><strong>Public policy text only</strong><small>Never your witness, secret, wallet address, or vote.</small></div><button className="text-button">Explain the two disclosures <ChevronRight size={16} /></button></section>
        <section id="results" className="metrics"><p className="eyebrow">Public ballot metrics</p><div><strong>0</strong><span>finalized proofs</span></div><div><strong>0%</strong><span>turnout</span></div><p className="small">No outcome is presented as final before an on-chain receipt is finalized.</p></section>
      </aside>
    </main>
    <footer id="help"><span>Ballot Boreal is a privacy-first civic voting prototype.</span><a href="https://docs.midnight.network/" target="_blank" rel="noreferrer">Midnight documentation ↗</a></footer>
  </div>
}
